# Generated by Django 5.1.3 on 2024-12-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationsku',
            name='formulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicationsku',
            name='medication_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicationsku',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
